apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "elsa.fullname" . }}
  labels:
    app: {{ template "elsa.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "elsa.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "elsa.name" . }}
    spec:
      containers:
      - name: elsa
        image: {{ .Values.docker_server }}/elsa:{{ .Values.image.tag }}
        imagePullPolicy: Always
        {{- if .Values.securityContext.enabled }}
        securityContext:
          capabilities:
            drop:
            - ALL
        {{- end }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }} 
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }} 
        env:
{{ toYaml .Values.env | indent 10 }} 
        ports:
        - containerPort: 8080
        resources:
{{ toYaml .Values.resources | indent 10 }}