apiVersion: v1
kind: Service
metadata:
  name: {{ template "elsa.fullname" . }}
  labels:
    app: {{ template "elsa.name" . }}
spec:
  ports:
  - port: 8080
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "elsa.name" . }}