
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build
  namespace: elsa-lab
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build
  namespace: elsa-lab
subjects:
- kind: ServiceAccount
  name: build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-role-binding
  namespace: elsa-lab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins
---
